//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCreditSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public CLIENT()
        {
            this.CREDIT = new HashSet<CREDIT>();
        }
    
        public int CLIENT_ID { get; set; }
        public string CLIENT_TYPE { get; set; }
        public string CLIENT_EGN_BULSTAT { get; set; }
        public string CLIENT_FULLNAME { get; set; }
        public string EMAIL { get; set; }
        public string TELEPHONE { get; set; }
        public string ADRESS_TEXT { get; set; }
        public string CLIENT_NOTE { get; set; }
        public Nullable<System.DateTime> MODIF_DATE { get; set; }
    
        public virtual ICollection<CREDIT> CREDIT { get; set; }
    }
}
