//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCreditSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDIT
    {
        public CREDIT()
        {
            this.CREDIT_PLAN = new HashSet<CREDIT_PLAN>();
        }
    
        public int CREDIT_ID { get; set; }
        public string CREDIT_NO { get; set; }
        public System.DateTime CREDIT_DATE { get; set; }
        public int CREDIT_PERIOD { get; set; }
        public System.DateTime CREDIT_END_DATE { get; set; }
        public System.DateTime CREDIT_BEGIN_DATE { get; set; }
        public int CLIENT_ID { get; set; }
        public Nullable<int> PROD_CODE { get; set; }
        public decimal CREDIT_SUM { get; set; }
        public string CREDIT_NOTE { get; set; }
        public Nullable<System.DateTime> MODIF_DATE { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual ICollection<CREDIT_PLAN> CREDIT_PLAN { get; set; }
        public virtual CREDIT_PRODUCT CREDIT_PRODUCT { get; set; }
    }
}
