//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCreditSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDIT_PLAN
    {
        public int MATURITY_ID { get; set; }
        public Nullable<int> CREDIT_ID { get; set; }
        public System.DateTime MATURITY_DATE { get; set; }
        public decimal MATURITY_SUM { get; set; }
        public string MATURITY_NOTE { get; set; }
        public Nullable<System.DateTime> MODIF_DATE { get; set; }
    
        public virtual CREDIT CREDIT { get; set; }
    }
}
