//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCreditSystem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CreaditSystemEntities : DbContext
    {
        public CreaditSystemEntities()
            : base("name=CreaditSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<CREDIT> CREDIT { get; set; }
        public virtual DbSet<CREDIT_PLAN> CREDIT_PLAN { get; set; }
        public virtual DbSet<CREDIT_PRODUCT> CREDIT_PRODUCT { get; set; }
        public virtual DbSet<INTEREST> INTEREST { get; set; }
        public virtual DbSet<PROD_PERIODS> PROD_PERIODS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
