//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCreditSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEREST
    {
        public int PROD_CODE { get; set; }
        public int PROD_PERIOD { get; set; }
        public decimal SUM_FROM { get; set; }
        public decimal SUM_TO { get; set; }
    
        public virtual PROD_PERIODS PROD_PERIODS { get; set; }
    }
}
